### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by dencat** [gmu-swe/phosphor#108]
I catch VerifyError on simple program.
Step to reproduce:
1) create file App.java:
```
public class App {
	public static void main(String[] args)   {
       	 	String z = "1";
		String f2 = E.method(z);
	}
}
```
2) create file E.java:
```
public final class E {
    private E() {}

    public static String method(String a) {
        return "";
    }  
}
```

3) create file through.txt 
```
E.method(Ljava/lang/String;)Ljava/lang/String;
```

4) instrument java and compile application
```
java -jar Phosphor-0.0.4-SNAPSHOT.jar -multiTaint $JAVA_HOME INST_JAVA
javac E.java
javac App.java
```
5) run application
```
INST_JAVA/bin/java -Xbootclasspath/a:Phosphor-0.0.4-SNAPSHOT.jar -javaagent:Phosphor-0.0.4-SNAPSHOT.jar=taintThrough=through.txt   App
```
Output:
```
java.lang.VerifyError
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses0$$PHOSPHORTAGGED(InstrumentationImpl.java)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at edu.columbia.cs.psl.phosphor.SourceSinkTransformer.retransform(SourceSinkTransformer.java:77)
	at E.<clinit>(E.java)
	at App.main(App.java:5)
Exception in thread "main" java.lang.VerifyError
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses0$$PHOSPHORTAGGED(InstrumentationImpl.java)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at edu.columbia.cs.psl.phosphor.SourceSinkTransformer.retransform(SourceSinkTransformer.java:77)
	at E.<clinit>(E.java)
	at App.main(App.java:5)
```

**Comment by jon-bell** [comment]
The taintThrough semantics are:
If the receiver object of the taintThrough method is tainted, then the return value gets a copy of that same taint tag.

Hence, you can not specify a static method (or a constructor) as a taint through method.

I would be happy to help you with a PR to create a regression test for this, and add error handling code to check for this. You should take a look at the existing regression tests, and in edu.columbia.cs.psl.phosphor.instrumenter.TaintThroughTaintingMV

**Comment by dencat** [comment]
I will try to create patch, can you explain what exactly I should do?

**Comment by jon-bell** [comment]
Take a look at the existing integration tests for the auto Tainter - and add one that uses a static taint through method, causing the test to fail. Then, update the `TaintThroughTaintingMV` to detect if it's instrumenting a static method as a taint through, and if so, print an error.

**Comment by jon-bell** [comment]
Thank you for your contribution!
