### ISSUE TITLE
This feature requires ASM6

### ISSUE THREAD

**Issue by dencat** [gmu-swe/phosphor#113]
Sometimes exception "This feature requires ASM6" is thrown.
Do you have plans to upgrade asm version?

**Comment by jon-bell** [comment]
Phosphor uses ASM version 7.0 currently.

Can you provide more details?

**Comment by dencat** [comment]
I use last (1f1464cab00a24dfdb7a272c39494c9c3e5b8d0e) version of phosphor and try to instrument project "rundeck" - https://dl.bintray.com/rundeck/rundeck-maven/rundeck-3.0.21-20190424.war
java -jar Phosphor-0.0.4-SNAPSHOT.jar -multiTaint rundeck-3.0.21-20190424.war inst
This is cutted output:
```
Unable to process zip/jar: /tmp/265262545241473615WEB-INFlibjaxb-api-2.3.0.jar
java.lang.UnsupportedOperationException: This feature requires ASM6
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:130)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:715)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:535)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at edu.columbia.cs.psl.phosphor.Instrumenter.analyzeClass(Instrumenter.java:136)
	at edu.columbia.cs.psl.phosphor.Instrumenter._processZip(Instrumenter.java:665)
	at edu.columbia.cs.psl.phosphor.Instrumenter._processZip(Instrumenter.java:701)
	at edu.columbia.cs.psl.phosphor.Instrumenter.processZip(Instrumenter.java:649)
	at edu.columbia.cs.psl.phosphor.Instrumenter._main(Instrumenter.java:513)
	at edu.columbia.cs.psl.phosphor.Instrumenter.main(Instrumenter.java:392)
```
Or instrument just jaxp-api:
```
mkdir temp && cd temp
wget http://archive.ubuntu.com/ubuntu/pool/universe/j/jaxb-api/libjaxb-api-java_2.3.0-2_all.deb
ar x libjaxb-api-java_2.3.0-2_all.deb
tar xJf data.tar.xz
cd usr/share/java/
java -jar Phosphor-0.0.4-SNAPSHOT.jar -multiTaint jaxb-api.jar inst
```

```
Data flow tracking: enabled
Control flow tracking: disabled
Multi taint: enabled
Branch not taken: enabled
Starting analysis
Unable to process zip/jar: /tmp/temp/usr/share/java/jaxb-api.jar
java.lang.UnsupportedOperationException: This feature requires ASM6
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:130)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:715)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:535)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at edu.columbia.cs.psl.phosphor.Instrumenter.analyzeClass(Instrumenter.java:136)
	at edu.columbia.cs.psl.phosphor.Instrumenter._processZip(Instrumenter.java:665)
	at edu.columbia.cs.psl.phosphor.Instrumenter.processZip(Instrumenter.java:649)
	at edu.columbia.cs.psl.phosphor.Instrumenter._main(Instrumenter.java:513)
	at edu.columbia.cs.psl.phosphor.Instrumenter.main(Instrumenter.java:392)
Analysis Completed: Beginning Instrumentation Phase
java.lang.ArrayIndexOutOfBoundsException: 1
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintPassingMV.visitInvokeDynamicInsn(TaintPassingMV.java:2102)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:457)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:457)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:457)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.InvokeDynamicInsnNode.accept(InvokeDynamicInsnNode.java:84)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:792)
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintLoadCoercer$UninstTaintLoadCoercerMN.visitEnd(TaintLoadCoercer.java:657)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:778)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:813)
	at edu.columbia.cs.psl.phosphor.instrumenter.PrimitiveArrayAnalyzer$PrimitiveArrayAnalyzerMN.visitEnd(PrimitiveArrayAnalyzer.java:1300)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:778)
	at edu.columbia.cs.psl.phosphor.instrumenter.PrimitiveArrayAnalyzer.visitEnd(PrimitiveArrayAnalyzer.java:1594)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:778)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:813)
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor$4.visitEnd(TaintTrackingClassVisitor.java:531)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1279)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:294)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:107)
	at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:175)
	at edu.columbia.cs.psl.phosphor.Instrumenter$4.call(Instrumenter.java:672)
	at edu.columbia.cs.psl.phosphor.Instrumenter$4.call(Instrumenter.java:667)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 1
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintPassingMV.visitInvokeDynamicInsn(TaintPassingMV.java:2102)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:457)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:457)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:457)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.InvokeDynamicInsnNode.accept(InvokeDynamicInsnNode.java:84)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:792)
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintLoadCoercer$UninstTaintLoadCoercerMN.visitEnd(TaintLoadCoercer.java:657)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:778)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:813)
	at edu.columbia.cs.psl.phosphor.instrumenter.PrimitiveArrayAnalyzer$PrimitiveArrayAnalyzerMN.visitEnd(PrimitiveArrayAnalyzer.java:1300)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:778)
	at edu.columbia.cs.psl.phosphor.instrumenter.PrimitiveArrayAnalyzer.visitEnd(PrimitiveArrayAnalyzer.java:1594)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:778)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:813)
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor$4.visitEnd(TaintTrackingClassVisitor.java:531)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1279)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:294)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:107)
	at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:175)
	at edu.columbia.cs.psl.phosphor.Instrumenter$4.call(Instrumenter.java:672)
	at edu.columbia.cs.psl.phosphor.Instrumenter$4.call(Instrumenter.java:667)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
method so far:
Saving javax/xml/bind/ModuleUtil
java.lang.NullPointerException
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:130)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:100)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:195)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:100)
	at edu.columbia.cs.psl.phosphor.instrumenter.HidePhosphorFromASMCV.visit(HidePhosphorFromASMCV.java:23)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:524)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:294)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:107)
	at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:175)
	at edu.columbia.cs.psl.phosphor.Instrumenter$4.call(Instrumenter.java:672)
	at edu.columbia.cs.psl.phosphor.Instrumenter$4.call(Instrumenter.java:667)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:130)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:100)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:195)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:100)
	at edu.columbia.cs.psl.phosphor.instrumenter.HidePhosphorFromASMCV.visit(HidePhosphorFromASMCV.java:23)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:524)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:294)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:107)
	at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:175)
	at edu.columbia.cs.psl.phosphor.Instrumenter$4.call(Instrumenter.java:672)
	at edu.columbia.cs.psl.phosphor.Instrumenter$4.call(Instrumenter.java:667)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
method so far:
Saving module-info
Done after 1784 ms
```

**Comment by jon-bell** [comment]
I've bumped Phosphor to use ASM7, but note that Phosphor does not yet support Java 9, and the jars that you reference include Java 9 classes.
