### ISSUE TITLE
Tags on primitive values don't propagate accross function calls

### ISSUE THREAD

**Issue by lobax** [gmu-swe/phosphor#137]
If I tag a primitive type and pass it on as an argument to a method, the tag will disappear. 

Here's a basic test that shows this behavior:
```
public class PrimitivePropagationImplicitITCase {
    @Test
    public void testPrimitiveBooleanImplicitTagInMethod() {
        String label = "lbl";
        boolean bool = MultiTainter.taintedBoolean(true, label);
        String result = method(bool);
        assertTaintHasOnlyLabel(MultiTainter.getTaint(result), label);
    }

    private String method(boolean bool) {
        if (bool) {
           return "true";
        }
        else {
            return "false";
        }
    }
}
```

And the result when running `mvn verify`: 
```
testBooleanImplicitTagInMethod(edu.columbia.cs.psl.test.phosphor.runtime.PrimitivePropagationImplicitITCase)  Time elapsed: 0.055 sec  <<< FAILURE!
java.lang.AssertionError: null
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Error.<init>(Error.java:58)
	at java.lang.AssertionError.<init>(AssertionError.java:49)
	at org.junit.Assert.fail$$PHOSPHORTAGGED(Assert.java:86)
	at org.junit.Assert.assertTrue$$PHOSPHORTAGGED(Assert.java:41)
	at org.junit.Assert.assertNotNull$$PHOSPHORTAGGED(Assert.java:621)
	at org.junit.Assert.assertNotNull$$PHOSPHORTAGGED(Assert.java:631)
	at edu.columbia.cs.psl.test.phosphor.BaseMultiTaintClass.assertTaintHasOnlyLabel$$PHOSPHORTAGGED(BaseMultiTaintClass.java:49)
	at edu.columbia.cs.psl.test.phosphor.runtime.PrimitivePropagationImplicitITCase.testBooleanImplicitTagInMethod$$PHOSPHORTAGGED(PrimitivePropagationImplicitITCase.java:26)
```

**Comment by jon-bell** [comment]
This is not a problem with primitives or function calls - this is a problem of control flow versus dat flow. There is no direct data flow in `method`: the value of `bool` does not flow (through data flow) into the return value of `method`. Try doing the same test but with `controlTrack` enabled, which will propagate flows between control flow decisions (e.g. the `if` statement in `method`) and assignments (e.g. the `return` statements in `method`).

**Comment by lobax** [comment]
I believe I have `controlTrack` enabled, I'm running this test on Phosphor so it's running with the other tests on `maven-failsafe-plugin:2.18.1:integration-test (integration-test-implicit-tracking)`. 

The following works: 
```
@Test
    public void testBooleanImplicitTag() {
        String label = "lbl";
        boolean bool = MultiTainter.taintedBoolean(true, label);
        String result;
        if (bool) {
            result = "true";
        }
        else {
            result = "false";
        }
        assertTaintHasOnlyLabel(MultiTainter.getTaint(result), label);
    }
```

**Comment by jon-bell** [comment]
What revision and flags are you using? This passes on master (c3b21793659fb9061c579e353a5c5c9829d593f9).

**Comment by lobax** [comment]
Ah, I'm on `ffadeabf`, I'll rebuild and see if it works. I've used `instrumentJRE.sh` to generate the instrumented JRE's, so `-controlTrack -forceUnboxAcmpEq -withEnumsByValue`

**Comment by lobax** [comment]
It passes now! Thank you.
