### ISSUE TITLE
incompatible with ASM in SpringBoot

### ISSUE THREAD

**Issue by coder-chenzhi** [gmu-swe/phosphor#150]
To track the data flow, Phosphor needs to add wrapper methods to existing classes and patch the calls to Java Reflection. Specifically, Phosphor calls the ReflectionMasker.addTypeParams() to get the actual parameter list of the wrapper methods. However, **these wrapper methods are not transparent to ASM in SpringBoot**. We find out one place where SpringBoot uses ASM to visit the method lists of classes and make calls to them. Thus, **Phosphor will add type parameters to wrapper methods again, and NoSuchMethodException throws**. I think we can solve this issue via a sanity check to determine if the parameter list is already tainted. 
I will create a PR later.

## How to repoduce
To repoduce this issue, you need to
- create a maven projects with following code and pom.xml
- build the fat jar
- instrument the fat jar with Phosphor
- run the instrumented fat jar with Phosphor

```java
package com.alibaba.test;
import org.springframework.asm.*;
import java.io.IOException;
import java.lang.reflect.Member;
import java.util.HashMap;
import java.util.Map;
/**
 * Test case to reproduce the bug of ReflectionMasker.addTypeParams
 * The class visitor retrieve all methods and its parameters by VisitMethod
 */
public class ReflectionAddTypeParams {
    public static void main(String[] args)
            throws IOException, ClassNotFoundException {
        String className = "com.alibaba.test.Person";
        ClassReader reader = new ClassReader(className);
        Class clazz = Class.forName(className);
        Map<Member, Type[]> map = new HashMap<>();
        reader.accept(new MyClassVisitor(clazz, map), 0);
    }
}
class Person {
    String name;
    public Person(String name) {
        this.name = name;
    }
}
class MyClassVisitor extends ClassVisitor {
    private final Class<?> clazz;
    private final Map<Member, Type[]> memberMap;
    public MyClassVisitor(Class<?> clazz, Map<Member, Type[]> map) {
        super(SpringAsmInfo.ASM_VERSION);
        this.clazz = clazz;
        this.memberMap = map;
    }
    @Override
    public MethodVisitor visitMethod(int access, String name, String desc, String signature, String[] exceptions) {
        Type[] args = Type.getArgumentTypes(desc);
        Class<?>[] argTypes = new Class<?>[args.length];
        for (int i = 0; i < args.length; i++) {
            try {
                argTypes[i] = Class.forName(args[i].getClassName());
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }
        }
        try {
            if ("<init>".equals(name)) {
                memberMap.put(this.clazz.getConstructor(argTypes), args);
            } else {
                memberMap.put(this.clazz.getMethod(name, argTypes), args);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
       
        return super.visitMethod(access, name, desc, signature, exceptions);
    }
}
```

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example</groupId>
  <artifactId>PhosphorBug</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>PhosphorBug</name>
  <url>http://www.example.com</url>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>4.3.25.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
      <plugins>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <!-- Maven Shade Plugin -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-shade-plugin</artifactId>
          <version>2.3</version>
          <executions>
            <!-- Run shade goal on package phase -->
            <execution>
              <phase>package</phase>
              <goals>
                <goal>shade</goal>
              </goals>
              <configuration>
                <transformers>
                  <!-- add Main-Class to manifest file -->
                  <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                    <mainClass>com.alibaba.test.ReflectionAddTypeParams</mainClass>
                  </transformer>
                </transformers>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
  </build>
</project>
```

## The stack trace of exception
We can see that the original constructor of class `Person` is `com.alibaba.test.Person.<init>(java.lang.String)`. The constructor after instrumentation should be `com.alibaba.test.Person.<init>(edu.columbia.cs.psl.phosphor.runtime.Taint, java.lang.String, edu.columbia.cs.psl.phosphor.runtime.Taint)`. However, the actual called constructor is `com.alibaba.test.Person.<init>(edu.columbia.cs.psl.phosphor.runtime.Taint, edu.columbia.cs.psl.phosphor.runtime.Taint, edu.columbia.cs.psl.phosphor.runtime.Taint, java.lang.String, edu.columbia.cs.psl.phosphor.runtime.Taint, edu.columbia.cs.psl.phosphor.runtime.Taint, edu.columbia.cs.psl.phosphor.runtime.Taint)`
```
java.lang.NoSuchMethodException: com.alibaba.test.Person.<init>(edu.columbia.cs.psl.phosphor.runtime.Taint, edu.columbia.cs.psl.phosphor.runtime.Taint, edu.columbia.cs.psl.phosphor.runtime.Taint, java.lang.String, edu.columbia.cs.psl.phosphor.runtime.Taint, edu.columbia.cs.psl.phosphor.runtime.Taint, edu.columbia.cs.psl.phosphor.runtime.Taint)
        at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
        at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:784)
        at java.lang.Throwable.<init>(Throwable.java:266)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:56)
        at java.lang.NoSuchMethodException.<init>(NoSuchMethodException.java:51)
        at java.lang.Class.getConstructor0$$PHOSPHORTAGGED(Class.java:3082)
        at java.lang.Class.getConstructor$$PHOSPHORTAGGED(Class.java:1825)
        at com.alibaba.test.MyClassVisitor.visitMethod$$PHOSPHORTAGGED(ReflectionAddTypeParams.java:69)
        at org.springframework.asm.ClassReader.readMethod$$PHOSPHORTAGGED(ClassReader.java:1061)
        at org.springframework.asm.ClassReader.accept$$PHOSPHORTAGGED(ClassReader.java:729)
        at org.springframework.asm.ClassReader.accept$$PHOSPHORTAGGED(ClassReader.java:527)
        at com.alibaba.test.ReflectionAddTypeParams.main$$PHOSPHORTAGGED(ReflectionAddTypeParams.java:24)
        at com.alibaba.test.ReflectionAddTypeParams.main(ReflectionAddTypeParams.java)
java.lang.NoSuchMethodException: com.alibaba.test.Person.<clinit>()
        at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
        at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:784)
        at java.lang.Throwable.<init>(Throwable.java:266)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:56)
        at java.lang.NoSuchMethodException.<init>(NoSuchMethodException.java:51)
        at java.lang.Class.getMethod$$PHOSPHORTAGGED(Class.java:1786)
        at java.lang.Class.getMethod(Class.java:0)
        at edu.columbia.cs.psl.phosphor.runtime.ReflectionMasker.getMethod(ReflectionMasker.java:331)
        at com.alibaba.test.MyClassVisitor.visitMethod$$PHOSPHORTAGGED(ReflectionAddTypeParams.java:71)
        at org.springframework.asm.ClassReader.readMethod$$PHOSPHORTAGGED(ClassReader.java:1061)
        at org.springframework.asm.ClassReader.accept$$PHOSPHORTAGGED(ClassReader.java:729)
        at org.springframework.asm.ClassReader.accept$$PHOSPHORTAGGED(ClassReader.java:527)
        at com.alibaba.test.ReflectionAddTypeParams.main$$PHOSPHORTAGGED(ReflectionAddTypeParams.java:24)
        at com.alibaba.test.ReflectionAddTypeParams.main(ReflectionAddTypeParams.java)
```

**Comment by jon-bell** [comment]
FYI, we're not sure that the patch that you have suggested will be a long-term fix for this. Another approach (if the class visitor is just reading the class data instead of writing it) is to hide Phosphor's generated code from that class visitor (see `HidePhosphorFromASMCV` for this approach).
