### ISSUE TITLE
"Could not allocate library name" when load native library by JNA.

### ISSUE THREAD

**Issue by Icysandwich** [gmu-swe/phosphor#164]
I tried to load my c library using the following code.
```java
Native.register(com.sun.jna.NativeLibrary.getInstance("c", Collections.emptyMap()));
```
When Phosphor applied, a fatal error occurs. Here's the information:
```
FATAL ERROR in native method: Could not allocate library name
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader$NativeLibrary.load$$PHOSPHORTAGGED(ClassLoader.java)
	at java.lang.ClassLoader.loadLibrary0$$PHOSPHORTAGGED(ClassLoader.java:1934)
	- locked <0x00000007212e82e8> (a java.util.Vector)
	- locked <0x00000007212cffc8> (a java.util.Vector)
	at java.lang.ClassLoader.loadLibrary$$PHOSPHORTAGGED(ClassLoader.java:1838)
	at java.lang.Runtime.loadLibrary0$$PHOSPHORTAGGED(Runtime.java:871)
	- locked <0x00000007214f7000> (a java.lang.Runtime)
	at java.lang.System.loadLibrary$$PHOSPHORTAGGED(System.java:1122)
	at java.awt.Toolkit$3.run$$PHOSPHORTAGGED(Toolkit.java:1636)
	at java.awt.Toolkit$3.run$$PHOSPHORTAGGED(Toolkit.java:1634)
	at java.awt.Toolkit$3.run(Toolkit.java:0)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged$$PHOSPHORTAGGED(AccessController.java)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1670)
	at java.awt.Component.<clinit>(Component.java:593)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName0$$PHOSPHORTAGGED(Class.java)
	at java.lang.Class.forName$$PHOSPHORTAGGED(Class.java:264)
	at java.lang.Class.forName(Class.java:0)
	at edu.columbia.cs.psl.phosphor.Instrumenter.isCollection(Instrumenter.java:67)
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visitEnd(TaintTrackingClassVisitor.java:1066)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:326)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visitEnd(OurSerialVersionUIDAdder.java:330)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:326)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:692)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:269)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:174)
	at edu.columbia.cs.psl.phosphor.PhosphorBaseTransformer.signalAndTransform(PhosphorBaseTransformer.java:62)
	at edu.columbia.cs.psl.phosphor.PhosphorBaseTransformer.transform$$PHOSPHORTAGGED(PhosphorBaseTransformer.java:31)
	at sun.instrument.TransformerManager.transform$$PHOSPHORTAGGED(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform$$PHOSPHORTAGGED(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:0)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass1$$PHOSPHORTAGGED(ClassLoader.java)
	at java.lang.ClassLoader.defineClass$$PHOSPHORTAGGED(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass$$PHOSPHORTAGGED(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass$$PHOSPHORTAGGED(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100$$PHOSPHORTAGGED(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run$$PHOSPHORTAGGED(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run$$PHOSPHORTAGGED(URLClassLoader.java:363)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:0)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged$$PHOSPHORTAGGED(AccessController.java)
	at java.net.URLClassLoader.findClass$$PHOSPHORTAGGED(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass$$PHOSPHORTAGGED(ClassLoader.java:418)
	- locked <0x0000000721230610> (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass$$PHOSPHORTAGGED(Launcher.java:355)
	at java.lang.ClassLoader.loadClass$$PHOSPHORTAGGED(ClassLoader.java:351)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:0)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:84)
	at jna.Main.main$$PHOSPHORTAGGED(Main.java:6)
	at jna.Main.main(Main.java)
```

My JNA version is 4.2.2. The pom info is as follows
```
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>4.2.2</version>
</dependency>
```

Could you help figure out what happens?

**Comment by jon-bell** [comment]
What version of Phosphor are you using? Line 64 in Instrumenter.java is `return false`, which seems unlikely to be the culprit.

If you would like me/us to debug this, please provide:
* A maven project that contains a minimum example to reproduce, including your C library (preferably with the source to your library and a build script that compiles it). 
* The revision of Phosphor (git commit SHA) you are using
* The exact JVM version you are using
* The exact command you used to run this

**Comment by Icysandwich** [comment]
Sorry for lacking information.
I create a maven project. See [https://github.com/Icysandwich/phosphortest](url) PLZ.
I use the newest Phosphor. (Error log above is also changed.)
Java version is 1.8.0_261.
Commands:

1. Enter the project phosphortest. Using ``` mvn package ``` to build.
2. Using phosphor to run the class file: ``` bin/java -Xbootclasspath/a:Phosphor-0.0.5-SNAPSHOT.jar -javaagent:Phosphor-0.0.5-SNAPSHOT.jar -cp phosphortest/target/jna-0.0.1-SNAPSHOT-jar-with-dependencies.jar jna.Main ```

Finally you can get the above error info. 

The c library is standard libc.so for linux. The library can be changed to any other libs.
This problem seems not occur on Windows.

**Comment by YuGao-Space** [comment]
I think the problem is that we cannot call `Class.forName(name)` in Phosphor code when running it on Linux. Here `name ` refers to a class that starts with `java.awt`

**Comment by jon-bell** [comment]
The code sample that you provided does not contain the line that you say is error-inducing (`Native.register(com.sun.jna.NativeLibrary.getInstance("c", Collections.emptyMap()));`). When I run the sample that you have in git:
```java
public class Main {

	public static void main(String[] args) {
		com.sun.jna.NativeLibrary.getInstance("c");
	}

}
```
With and without phosphor, the code runs and terminates with no exception. I am on Mac. Is this problem exclusive to Linux, or does it require the `register` call to trigger?

**Comment by Icysandwich** [comment]
Yeah it is exclusive to Linux. I tried it on Windows and it runs all right too.
No need ```register``` call here.

**Comment by yu-wch** [comment]
Hi, when I run the following test code on Linux:

```
public class Main {

	public static void main(String[] args) {
		com.sun.jna.NativeLibrary.getInstance("c");
	}

}
```

I will get the error: `FATAL ERROR in native method: Could not allocate library name`.

When I tried to skip all the classes whoes name starts with "java/awt" in `Instrumenter.isCollection`, everything will be fine.

However, whe I use the following test code on Linux and skip all the "java/awt" classes:

```
public class Main {

	public static void main(String[] args) {
		Native.register(com.sun.jna.NativeLibrary.getInstance("c"));
	}

}
```

I will got the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'indexOf': fav-jre-inst/bin/java: undefined symbol: indexOf
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:784)
	at java.lang.Throwable.<init>(Throwable.java:266)
	at java.lang.Error.<init>(Error.java:70)
	at java.lang.LinkageError.<init>(LinkageError.java:55)
	at java.lang.UnsatisfiedLinkError.<init>(UnsatisfiedLinkError.java:54)
	at com.sun.jna.Function.<init>(Function.java:212)
	at com.sun.jna.NativeLibrary.getFunction$$PHOSPHORTAGGED(NativeLibrary.java:541)
	at com.sun.jna.NativeLibrary.getFunction$$PHOSPHORTAGGED(NativeLibrary.java:518)
	at com.sun.jna.NativeLibrary.getFunction$$PHOSPHORTAGGED(NativeLibrary.java:504)
	at com.sun.jna.Native.register$$PHOSPHORTAGGED(Native.java:1655)
	at com.sun.jna.Native.register$$PHOSPHORTAGGED(Native.java:1261)
	at jna.Main.main$$PHOSPHORTAGGED(Main.java:8)
	at jna.Main.main(Main.java)
```

**Comment by jon-bell** [comment]
Ok - in testing on a Ubuntu VM, `2e57a6f` seems to resolve the issue and now the example runs. Does this revision fix things on your end?

**Comment by Icysandwich** [comment]
Problem fixed! Thanks a lot!
Sorry for bothering you again, but I find a new issue. See [165](https://github.com/gmu-swe/phosphor/issues/165) PLZ.
