### ISSUE TITLE
Crashes inside MethodHandleImpl

### ISSUE THREAD

**Issue by aoli-al** [gmu-swe/phosphor#188]
Phosphor crashes while using MethodHandles. Here is the simplified program:

```
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.util.ServiceLoader;


public class Test {
  private static final MethodType LOAD_CLASS_CLASSLOADER = MethodType.methodType(ServiceLoader.class, Class.class,
            ClassLoader.class);
  public static void main(String[] args) throws Throwable {
        MethodHandles.Lookup publicLookup = MethodHandles.lookup();
        final MethodHandle handle = publicLookup.findStatic(ServiceLoader.class, "load", LOAD_CLASS_CLASSLOADER);
        final ServiceLoader serviceLoader = (ServiceLoader) handle.invokeExact(Test.class, Test.class.getClassLoader());
        System.out.println(serviceLoader);

  }
}
```
Stack trace:

```
Exception in thread "main" java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract ja
va.lang.invoke.BoundMethodHandle copyWithExtendL(java.lang.invoke.MethodType, java.lang.invoke.LambdaForm, java.
lang.Object, edu.columbia.cs.psl.phosphor.runtime.PhosphorStackFrame)' of abstract class java.lang.invoke.BoundM
ethodHandle.                                                                                                    
        at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:328)   
        at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:260)           
        at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:377)           
        at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:885)                        
        at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java)                            
        at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:869)                                
        at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java)                                    
        at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.prepareForInvoker(MethodHandleImpl.java:1187) 
        at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.bindCaller(MethodHandleImpl.java:1146)        
        at java.base/java.lang.invoke.MethodHandleImpl.bindCaller(MethodHandleImpl.java:1126)                   
        at java.base/java.lang.invoke.MethodHandles$Lookup.maybeBindCaller(MethodHandles.java:4011)             
        at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:3995)       
        at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethod(MethodHandles.java:3932)             
        at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2596)                  
        at Test.main(Test.java:12)                                                                              
        at Test.main(Test.java) 
```

My current workaround is to disable instrumentation in MethodHandleImpl

**Comment by jon-bell** [comment]
I see that this test crashes, but with a different error - a [ClassCastException](https://github.com/gmu-swe/phosphor/actions/runs/4039084693/jobs/6943531235#step:5:2100). I am working on a patch for this error - but am not seeing the `AbstractMethodError` that you report. What JVM version are you using?

**Comment by aoli-al** [comment]
I'm using java-16

```
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Corretto-16.0.2.7.1 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Corretto-16.0.2.7.1 (build 16.0.2+7, mixed mode, sharing)
```

**Comment by jon-bell** [comment]
FYI, I have been working on a more complete patch for this in 5b24fa5f639ee3d4d64263cef8515a3141578325 . This feels more correct (to add wrappers where they were missing), but will take a bit longer to get perfect: it's now passing the regression test suite (including your example), but when running DaCapo I'm seeing assertion errors in GC.

**Comment by aoli-al** [comment]
This sounds great! Thank you a lot for maintaining such a great tool!

**Comment by jon-bell** [comment]
Looks like everything is passing now with these last changes. Good luck, and let me know if you run into any other issues.
