### ISSUE TITLE
I get this error after completing the  for instrumented  jre

### ISSUE THREAD

**Issue by wangmanyou** [gmu-swe/phosphor#203]
I get this error after completing the  for instrumented  jre for jdk8. in linux

wangmanyou@wangmanyou-virtual-machine:~$ java -version
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: edu/columbia/cs/psl/phosphor/struct/TaintedWithObjTag

**Comment by wangmanyou** [comment]
When I switched to jdk9 successfully, but run the example that you hava procide occur this error, what is the reason?
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.josecambronero.ObjectTagExamples.main(ObjectTagExamples.java:112)
Caused by: java.lang.IllegalStateException: Calling uninstrumented Phosphor stubs!
	at edu.columbia.cs.psl.phosphor.runtime.MultiTainter.taintedDouble(MultiTainter.java:193)
	at com.josecambronero.ObjectTagExamples.testExample3(ObjectTagExamples.java:49)
	... 5 more

**Comment by jon-bell** [comment]
@wangmanyou - It is extremely difficult to diagnose what went wrong when you only post this error. Please copy/paste the textual commands that you ran (from instrumenting the JVM to running), and all of their output.
