### ISSUE TITLE
NPE when running DaCapo instrumented with multiTaint

### ISSUE THREAD

**Issue by Waldo1637** [gmu-swe/phosphor#63]
Phosphor built via `mvn package` from commit 8d396effcf461d40b83e614c77d1461173caf945 (i.e. master branch of Programming-Systems-Lab/phosphor).
Only change from that commit was modifying the taint-sources and taint-sinks files to use the lines which are currently commented (i.e. the sources and sinks in the standard java library) and updating the `instrumentJRE.sh` and `runDacapo.sh` scripts to use the aforementioned files.

When the `runDacapo.sh` script gets to the point of running the benchmarks instrumented using object tags, every benchmark gives the following exception:
```
Exception in thread "main" java.lang.NullPointerException
    at edu.columbia.cs.psl.phosphor.runtime.TaintSourceWrapper.setTaints(TaintSourceWrapper.java:122)
    at edu.columbia.cs.psl.phosphor.runtime.TaintSourceWrapper.autoTaint(TaintSourceWrapper.java:128)
    at java.io.FileInputStream.read$$PHOSPHORTAGGED(FileInputStream.java)
    at sun.misc.Resource.getBytes$$PHOSPHORTAGGED(Resource.java:124)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass$$PHOSPHORTAGGED(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass$$PHOSPHORTAGGED(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at sun.launcher.LauncherHelper.checkAndLoadMain$$PHOSPHORTAGGED(LauncherHelper.java:495)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java)
```
In TaintSourceWrapper.[setTaints(LazyArrayObjTags,String)](https://github.com/Programming-Systems-Lab/phosphor/blob/8d396effcf461d40b83e614c77d1461173caf945/Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/TaintSourceWrapper.java#L118-L125), some `Taint` reference from the `LazyArrayObjTags.taints` array is `null`. 

If I understand correctly, the `null` Taint simply means that the 
corresponding element from the data array is not tainted meaning this is a normal case that should be handled (maybe by simply replacing the `null` reference with `retTaint`?).

**Comment by jon-bell** [comment]
That's correct - cb5d6410e6cd537b57c07f8f09806efc754ad273 should fix it. Let me know if this does it for you - I'm also happy to accept PR's for fixes.

**Comment by Waldo1637** [comment]
The change avoided the NPE but the assignment to `t` is not actually saving to the backing array. I will submit a fix.
