### ISSUE TITLE
java.lang.AbstractMethodError: java.util.stream.IntPipeline$$Lambda$5/1132547352.applyAsInt$$PHOSPHORTAGGED

### ISSUE THREAD

**Issue by miguelvelezmj25** [gmu-swe/phosphor#68]
Hello Professor,

I instrumented a demo workload of lucene with int tags and got the following error:

```
Exception in thread "main" java.lang.AbstractMethodError: java.util.stream.IntPipeline$$Lambda$5/1525037790.applyAsInt$$PHOSPHORTAGGED(IIIILedu/columbia/cs/psl/phosphor/struct/TaintedIntWithIntTag;)Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithIntTag;
	at java.util.stream.ReduceOps$5ReducingSink.accept$$PHOSPHORTAGGED(ReduceOps.java:258)
	at java.util.Spliterators$IntArraySpliterator.forEachRemaining(Spliterators.java:1032)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.IntPipeline.reduce$$PHOSPHORTAGGED(IntPipeline.java:456)
	at java.util.stream.IntPipeline.sum$$PHOSPHORTAGGED(IntPipeline.java:414)
	at org.apache.lucene.util.bkd.BKDWriter.writeLeafBlockPackedValues$$PHOSPHORTAGGED(BKDWriter.java:1274)
	at org.apache.lucene.util.bkd.BKDWriter.access$1200$$PHOSPHORTAGGED(BKDWriter.java:82)
	at org.apache.lucene.util.bkd.BKDWriter$OneDimensionBKDWriter.writeLeafBlock(BKDWriter.java:697)
	at org.apache.lucene.util.bkd.BKDWriter$OneDimensionBKDWriter.finish$$PHOSPHORTAGGED(BKDWriter.java:626)
	at org.apache.lucene.util.bkd.BKDWriter.writeField1Dim$$PHOSPHORTAGGED(BKDWriter.java:519)
	at org.apache.lucene.util.bkd.BKDWriter.writeField$$PHOSPHORTAGGED(BKDWriter.java:427)
	at org.apache.lucene.codecs.lucene60.Lucene60PointsWriter.writeField(Lucene60PointsWriter.java:105)
	at org.apache.lucene.index.PointValuesWriter.flush(PointValuesWriter.java:183)
	at org.apache.lucene.index.DefaultIndexingChain.writePoints(DefaultIndexingChain.java:204)
	at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:139)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:470)
	at org.apache.lucene.index.DocumentsWriter.doFlush$$PHOSPHORTAGGED(DocumentsWriter.java:554)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads$$PHOSPHORTAGGED(DocumentsWriter.java:719)
	at org.apache.lucene.index.IndexWriter.doFlush$$PHOSPHORTAGGED(IndexWriter.java:3595)
	at org.apache.lucene.index.IndexWriter.flush$$PHOSPHORTAGGED(IndexWriter.java:3570)
	at org.apache.lucene.index.IndexWriter.shutdown(IndexWriter.java:1028)
	at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1071)
	at org.apache.lucene.demo.IndexFiles.main(IndexFiles.java:123)
```

Based on what you told me about AbstractMethodErrors, it seems that the implementation of applyAsInt, which I guess comes from a lambda expression, is not instrumented.

I have attached the 4 original jar files needed to run the demo. I instrumented all of them. The main class is org.apache.lucene.demo.IndexFiles. It takes one program argument, [-docs DOCS_PATH]. I passed the Phosphor's src directory as the path and got the error.

[lucene.zip](https://github.com/gmu-swe/phosphor/files/2383562/lucene.zip)

Is it correct that there might be some class file not being instrumented by the java agent? Thanks.

**Comment by jon-bell** [comment]
What exact version of Java (java -version)? 

As long as you are passing the java agent on the command line it *should* be instrumenting everything.

**Comment by miguelvelezmj25** [comment]
```
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

**Comment by jon-bell** [comment]
OK, I'll download and take a look later today. Out of curiosity - can you try on an older version of Java 8? Maybe <= 1.8.0_101?

**Comment by miguelvelezmj25** [comment]
Thanks. 

I will check an older version and let you know.

**Comment by miguelvelezmj25** [comment]
I just tried it with 1.8.0_101 and 1.8.0_91 with the same error.

**Comment by jon-bell** [comment]
Still not quite there - it's getting past this and hitting another lambda-related issue, I'll keep working on it.

**Comment by miguelvelezmj25** [comment]
I just tried instrumenting the four lucene jars and running the example listed above, but I am still getting the same error. I have the latest phosphor. Is there a flag that I need to select for this changes to work?

**Comment by jon-bell** [comment]
Still on int tags, right?

**Comment by jon-bell** [comment]
It works for me on int, obj, and implicit tags on Phosphor 7c2d398a94c44b73228373313ddbccf9c2923d57 and java version "1.8.0_151"

**Comment by miguelvelezmj25** [comment]
I want to run it with implicit tags, and I do have the latest Phosphor code. I am working on a new branch where I am adding my own changes, but I am instrumenting the files with the default settings. I will keep working on my environment and let you know. Thanks.

**Comment by miguelvelezmj25** [comment]
Yes, it was the java version. I was using "1.8.0_162" and was getting the same error as above. I now used your version and it works fine. Thank you!

**Comment by jon-bell** [comment]
Ok that is weird - I will take a look on a newer version.

**Comment by miguelvelezmj25** [comment]
Thanks.

**Comment by jon-bell** [comment]
:( I went up to 1.8.0_181 (latest) and lucene worked fine with both int and implicit tags. I'm on limited bandwidth right now so can't download 1.8.0_162 but will give it a try later.

**Comment by miguelvelezmj25** [comment]
Did you make changes? Maybe there is a bug in 1.8.0_162?

**Comment by jon-bell** [comment]
I made no changes. It just worked on my machine on 1.8.0_162 w/ implicit tags too. Maybe there was something stale when you last tried.
