### ISSUE TITLE
Problem with tomcat 9.0.17 startup

### ISSUE THREAD

**Issue by dencat** [gmu-swe/phosphor#97]
Hi,
I try to run instrumented [tomcat 9.0.17](https://tomcat.apache.org/download-90.cgi), but it isn't work:
```
java.lang.IllegalArgumentException: argument type mismatch
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
	at java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java:52)
	at java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke0$$PHOSPHORTAGGED(NativeMethodAccessorImpl.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke$$PHOSPHORTAGGED(NativeMethodAccessorImpl.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke$$PHOSPHORTAGGED(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke$$PHOSPHORTAGGED(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.setAwait$$PHOSPHORTAGGED(Bootstrap.java:422)
	at org.apache.catalina.startup.Bootstrap.main$$PHOSPHORTAGGED(Bootstrap.java:490)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java)
```
Phosphor was launched with "-controlTrack" argument.
Do you have any idea what happened?
Thank you!

**Comment by jon-bell** [comment]
Can you give more precise steps to reproduce? What command did you use to instrument the JRE, and what command did you use to start Tomcat?

**Comment by dencat** [comment]
OS: Ubuntu 16.04 x64

Instrument the JRE:
```
java -jar Phosphor-0.0.4-SNAPSHOT.jar -controlTrack $JAVA_HOME java_inst
```
Download and extract tomcat:
```
wget https://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.17/bin/apache-tomcat-9.0.17.tar.gz
tar xzf apache-tomcat-9.0.17.tar.gz
cd apache-tomcat-9.0.17/bin
```
Set environment variables:
```
export JAVA_HOME=PATH_TO_java_inst
export JRE_HOME=PATH_TO_java_inst
export JAVA_OPTS=" -Xbootclasspath/a:PATH_TO_Phosphor-0.0.4-SNAPSHOT.jar  -javaagent:PATH_TO_Phosphor-0.0.4-SNAPSHOT.jar "
```
Run tomcat:
```
./startup.sh 
```
Then see log:
```
cat ../logs/catalina.out
```

```
java.lang.IllegalArgumentException: argument type mismatch
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
	at java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java:52)
	at java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke0$$PHOSPHORTAGGED(NativeMethodAccessorImpl.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke$$PHOSPHORTAGGED(NativeMethodAccessorImpl.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke$$PHOSPHORTAGGED(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke$$PHOSPHORTAGGED(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.setAwait$$PHOSPHORTAGGED(Bootstrap.java:422)
	at org.apache.catalina.startup.Bootstrap.main$$PHOSPHORTAGGED(Bootstrap.java:490)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java)
```

[Bootstrap.java#L422](https://github.com/apache/tomcat/blob/25d7c99e8c44a41a08ba85ccaba3cfec6af9c801/java/org/apache/catalina/startup/Bootstrap.java#L422):
```
        Method method =
            catalinaDaemon.getClass().getMethod("setAwait", paramTypes);
        method.invoke(catalinaDaemon, paramValues);
```

it seems something wrong with reflection

**Comment by jon-bell** [comment]
Should be all fixed now in master - big thanks to @katherine-hough for doing most of the heavy lifting.

FYI - if you pre-instrument tomcat: `java -jar Phosphor-0.0.4-SNAPSHOT.jar -controlTrack apache-tomcat apache-tomcat-inst` you'll find that it runs much, much much faster!
